name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: 'package.json'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        run: pnpm test

      - name: Build plugin
        run: pnpm build

      - name: Pack plugin
        run: pnpm sd:pack

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v3
        with:
          files: |
            *.streamDeckPlugin
